#!/bin/bash
#SBATCH --job-name=polartrain
#SBATCH -P a100
#SBATCH -N 1
#SBATCH --ntasks-per-node=12   
#SBATCH --gres=gpu:1
#SBATCH -A rvidal1-semantic_gpu ### this flag is required
#SBATCH -export=ALL
source  /data/apps/go.sh
cd /home/tboen1/data_rvidal1/tboen1/polar/Diff_NAS
source ./polarenv/bin/a
python3 polar_train.py  
