#!/bin/bash
#SBATCH -job-name=polartrain
#SBATCH -P a100
#SBATCH -N 1
#SBATCH -ntasks-per-node=48
#SBATCH --gres=gpu:1
#SBATCH -A tboen1_gpu    ###   this flag is required
#SBATCH -export=ALL

cd /home/tboen1/data_rvidal1/tboen1/polar/Diff_NAS
source ./polarenv/bin/activate
python polar_train.py

